trigger:
  branches:
    include:
      - main

pool:
  name: servicios  # Usar el agente self-hosted en la VM

stages:
  - stage: Deploy
    jobs:
      - job: DeployToVM
        steps:
          - checkout: self
          - script: |
              echo "Construyendo imágenes Docker..."
              cd /home/azureuser/
              docker-compose build
              docker-compose up -d
            displayName: "Construir y ejecutar contenedores"
